#!/usr/bin/env bash
seed=${1:+-s $1}

# Basic understanding
arvy-demo -d -a arrow --title "Arrow" $seed
arvy-demo -d -a ivy --title "Ivy" $seed

# For concurrency or a bit more complexity
arvy-demo -n 7 -a arrow --title "Arrow" $seed
arvy-demo -n 7 -a ivy --title "Ivy" $seed

# For showing how edgemin converges to an mst
arvy-demo -a edgemin --title "Edge Cost Minimizer" $seed &
arvy-demo -t mst -a arrow --title "Arrow with MST" $seed &
wait

# For showing how dynamic star converges to star
arvy-demo -a dynstar --title "Dynamic Star" $seed &
arvy-demo -t star -a arrow --title "Arrow with Star" $seed &
wait

# For showing how pairmin does a decent job
arvy-demo -a pairmin --title "Local Pair Distance Minimizer" $seed

# For checking best trees
arvy-demo -t star -a arrow --title "Arrow with Star" $seed
arvy-demo -t approxminpair -a arrow --title "Arrow with Approx Min Pairs" $seed

