#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export PATH="$(nix-build --no-out-link "$DIR/.." -A arvy)/bin:$PATH"

# Basic understanding
#arvy-demo -n 10 -t aminpair -a arrow --title "Arrow" -s 5
#arvy-demo -n 10 -t aminpair -a ivy --title "Ivy" -s 5
#
## For concurrency or a bit more complexity
#arvy-demo -n 7 -a arrow --title "Arrow"
#arvy-demo -n 7 -a ivy --title "Ivy"

# For showing how edgemin converges to an mst
arvy-demo -a edgemin --title "Edge Distance Minimizer" -s 0 &
arvy-demo -t mst -a arrow --title "Arrow with MST" -s 0 &
wait

arvy-demo -a pairmin --title "Local Pair Distance Minimizer" -s 0

# For showing how dynamic star converges to star
arvy-demo -a dynstar --title "Dynamic Star" -s 0 &
arvy-demo -t star -a arrow --title "Arrow with Star" -s 0 &
wait

# For checking best trees
#arvy-demo -t star -a arrow --title "Arrow with Star"
#arvy-demo -t approxminpair -a arrow --title "Arrow with Approx Min Pairs"
